# Generated by Django 4.2.4 on 2023-08-23 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_merge_0009_merge_20230811_1709_0010_alter_course_slug'),
        ('course', '0012_alter_coursecontent_video_courseprogress'),
    ]

    operations = [
    ]
