# Generated by Django 4.2.4 on 2023-08-24 13:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("course", "0013_alter_courseapply_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseapply",
            name="status",
            field=models.CharField(
                choices=[("Unpaid", "Unpaid"), ("Paid", "Paid")],
                default="Unpaid",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="courseapply",
            unique_together={("user", "course")},
        ),
    ]
