# Generated by Django 4.2.4 on 2023-08-24 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_alter_courseapply_user'),
        ('course', '0013_merge_20230823_1534'),
    ]

    operations = [
    ]
