# Generated by Django 4.2.4 on 2023-08-25 06:39

import course.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0014_alter_courseapply_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursecontent",
            name="source",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="courseapply",
            name="status",
            field=models.CharField(
                choices=[("Unpaid", "Unpaid"), ("Paid", "Paid")],
                default="Unpaid",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="coursecontent",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="videos/",
                validators=[course.utils.validate_video],
            ),
        ),
    ]
