# Generated by Django 4.2.4 on 2023-08-26 11:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0014_merge_20230824_1446"),
        ("course", "0015_coursecontent_source_alter_courseapply_status_and_more"),
    ]

    operations = []
