# Generated by Django 4.2.4 on 2023-08-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0015_coursecontent_source_alter_courseapply_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseapply",
            name="status",
            field=models.CharField(
                choices=[("Unpaid", "Unpaid"), ("Paid", "Paid")],
                default="Unpaid",
                max_length=20,
            ),
        ),
    ]
