# Generated by Django 4.2.4 on 2023-09-04 13:05

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0020_alter_courseapply_status_alter_coursecontent_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseapply",
            name="status",
            field=models.CharField(
                choices=[("Unpaid", "Unpaid"), ("Paid", "Paid")],
                default="Unpaid",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="coursecontent",
            name="source",
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
