# Generated by Django 4.2.4 on 2023-09-05 10:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0020_merge_20230904_1658"),
        ("course", "0022_alter_courseapply_status"),
    ]

    operations = []
