# Generated by Django 4.2.4 on 2023-09-08 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0023_alter_courseapply_status_alter_coursecontent_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursecontent",
            name="description_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="coursecontent",
            name="description_ru",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="coursecontent",
            name="description_uz",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="coursecontent",
            name="section_en",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contents",
                to="course.coursesection",
            ),
        ),
        migrations.AddField(
            model_name="coursecontent",
            name="section_ru",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contents",
                to="course.coursesection",
            ),
        ),
        migrations.AddField(
            model_name="coursecontent",
            name="section_uz",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contents",
                to="course.coursesection",
            ),
        ),
        migrations.AddField(
            model_name="coursecontent",
            name="title_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="coursecontent",
            name="title_ru",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="coursecontent",
            name="title_uz",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="courseapply",
            name="status",
            field=models.CharField(
                choices=[("Unpaid", "Unpaid"), ("Paid", "Paid")],
                default="Unpaid",
                max_length=20,
            ),
        ),
    ]
