# Generated by Django 4.2.4 on 2023-09-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0023_merge_20230905_1508"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseapply",
            name="status",
            field=models.CharField(
                choices=[("Unpaid", "Unpaid"), ("Paid", "Paid")],
                default="Unpaid",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="coursecontent",
            name="source",
            field=models.URLField(blank=True, null=True),
        ),
    ]
