# Generated by Django 4.2.4 on 2023-09-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0024_coursecontent_description_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseapply",
            name="status",
            field=models.CharField(
                choices=[("Unpaid", "Unpaid"), ("Paid", "Paid")],
                default="Unpaid",
                max_length=20,
            ),
        ),
    ]
