# Generated by Django 4.2.4 on 2023-09-11 10:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0024_alter_courseapply_status_alter_coursecontent_source"),
        ("course", "0025_alter_courseapply_status"),
    ]

    operations = []
