# Generated by Django 4.2.4 on 2023-09-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0026_alter_courseapply_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursesection",
            name="title_en",
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name="coursesection",
            name="title_ru",
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AddField(
            model_name="coursesection",
            name="title_uz",
            field=models.CharField(max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name="courseapply",
            name="status",
            field=models.CharField(
                choices=[("Unpaid", "Unpaid"), ("Paid", "Paid")],
                default="Unpaid",
                max_length=20,
            ),
        ),
    ]
