# Generated by Django 4.2.4 on 2023-09-11 10:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0026_alter_courseapply_status"),
        ("course", "0026_merge_20230911_1517"),
    ]

    operations = []
