# Generated by Django 4.2.4 on 2023-08-28 07:22

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0020_contactus_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutusfull",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="aboutusfull",
            name="name_ru",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="aboutusfull",
            name="name_uz",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="aboutusfull",
            name="text_en",
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name="aboutusfull",
            name="text_ru",
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name="aboutusfull",
            name="text_uz",
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
